# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20171203_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sn', models.CharField(max_length=30)),
                ('last_accessed', models.DateTimeField(null=True)),
            ],
        ),
    ]
