# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_bike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bike',
        ),
    ]
